version: 1.0.0.{build}
image: Visual Studio 2019
configuration:
- Debug
- Release
platform: Any CPU
clone_folder: C:\TheCrafters001\Build\EasyHTML\src\bin
before_build:
- ps: nuget restore 'C:\TheCrafters001\Build\EasyHTML\src\bin\src\EasyHTML.sln'
build:
  verbosity: minimal