Public Class ThemeSelect
    Private Sub Timer1_Tick(sender As Object, e As EventArgs) Handles Timer1.Tick
        If rad_Template.Checked = True Then
            grp_SelectTemplate.Enabled = True
            grp_exampleLoad.Enabled = False
        ElseIf rad_Blank.Checked = True Then
            grp_SelectTemplate.Enabled = False
            grp_exampleLoad.Enabled = False
        ElseIf rad_exampleLoad.Checked = True Then
            grp_SelectTemplate.Enabled = False
            grp_exampleLoad.Enabled = True
        End If
    End Sub

    Private Sub ThemeSelect_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        ' Set BackColor of main window
        Me.BackColor = Color.FromArgb(124, 63, 255)
        ' Set Default Theme to UI Kit
        cmb_Theme.SelectedIndex = 1
        ' cmb_exampleLoad.SelectedIndex = 0
        ' Make Blank by Default
        rad_Template.Checked = False
        rad_exampleLoad.Checked = False
        rad_Blank.Checked = True
        ' Start Timer
        Timer1.Start()
    End Sub

    Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        If rad_Blank.Checked = True And rad_Template.Checked = False Then
            Me.Close()
        ElseIf rad_Blank.Checked = False And rad_Template.Checked = True Then
            If cmb_Theme.Text = "" Then
                MessageBox.Show("Please select a template.", "No Template Selected", MessageBoxButtons.OK, MessageBoxIcon.Error)
            ElseIf cmb_Theme.Text = "UI Kit" Then
#Region "UI Kit"
                ' Generate UI Kit Template
                EasyHTML.mobileViewport_chkbox.Checked = True
                EasyHTML.UTF8_Set_chkbox.Checked = True
                EasyHTML.metatags_chkbox.Checked = True
                EasyHTML.siteAuthor_txtbox.Text = "TheCrafters001"
                EasyHTML.title_txtBox.Text = "EasyHTML Template"
                EasyHTML.revisit_txtBox.Text = "1"
                EasyHTML.description_txtBox.Text = "EasyHTML Template"
                EasyHTML.keywords_txtBox.Text = "easyhtml, template"
                EasyHTML.cssImport_lst.Items.Add("https://cdnjs.cloudflare.com/ajax/libs/uikit/3.5.4/css/uikit.min.css")
                EasyHTML.cssImport_lst.Items.Add("css/styles.css")
                EasyHTML.CodeEditorBox.Text = "<h1 align=""center"">UI Kit Template</h1><br><p align=""center"">This is the UI Kit Template generated by EasyHTML.</p>"
                EasyHTML.jsImport_lst.Items.Add("https://cdnjs.cloudflare.com/ajax/libs/uikit/3.5.4/js/uikit.min.js")
                EasyHTML.jsImport_lst.Items.Add("https://cdnjs.cloudflare.com/ajax/libs/uikit/3.5.4/js/uikit-icons.min.js")
                Me.Close()
#End Region
            ElseIf cmb_Theme.Text = "Bootstrap" Then
#Region "Bootstrap"
                ' Generate Bootstrap Template
                EasyHTML.mobileViewport_chkbox.Checked = True
                EasyHTML.UTF8_Set_chkbox.Checked = True
                EasyHTML.metatags_chkbox.Checked = True
                EasyHTML.siteAuthor_txtbox.Text = "TheCrafters001"
                EasyHTML.title_txtBox.Text = "EasyHTML Template"
                EasyHTML.revisit_txtBox.Text = "1"
                EasyHTML.description_txtBox.Text = "EasyHTML Template"
                EasyHTML.keywords_txtBox.Text = "easyhtml, template"
                EasyHTML.cssImport_lst.Items.Add("https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css")
                EasyHTML.pageTitle_txtBox.Text = "Hello, World!"
                EasyHTML.CodeEditorBox.Text = "<h1 align=""center"">Bootstrap Template</h1><br><p align=""center"">This is the Bootstrap Template generated by EasyHTML.</p>"
                EasyHTML.jsImport_lst.Items.Add("https://code.jquery.com/jquery-3.5.1.slim.min.js")
                EasyHTML.jsImport_lst.Items.Add("https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js")
                EasyHTML.jsImport_lst.Items.Add("https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js")
                Me.Close()
#End Region
            ElseIf cmb_Theme.Text = "W3.CSS" Then
#Region "W3.CSS"
                ' Generate W3.CSS Template
                EasyHTML.mobileViewport_chkbox.Checked = True
                EasyHTML.UTF8_Set_chkbox.Checked = True
                EasyHTML.metatags_chkbox.Checked = True
                EasyHTML.siteAuthor_txtbox.Text = "TheCrafters001"
                EasyHTML.title_txtBox.Text = "EasyHTML Template"
                EasyHTML.revisit_txtBox.Text = "1"
                EasyHTML.description_txtBox.Text = "EasyHTML Template"
                EasyHTML.keywords_txtBox.Text = "easyhtml, template"
                EasyHTML.cssImport_lst.Items.Add("https://www.w3schools.com/w3css/4/w3.css")
                EasyHTML.CodeEditorBox.Text = "<h1 align=""center"">W3.CSS Template</h1><br><p align=""center"">This is the W3.CSS Template generated by EasyHTML.</p>"
                EasyHTML.jsImport_lst.Items.Add("https://www.w3schools.com/lib/w3.js")
                Me.Close()
#End Region
            ElseIf cmb_Theme.Text = "Bulma" Then
#Region "Bulma"
                ' Generate Bulma Template
                EasyHTML.mobileViewport_chkbox.Checked = True
                EasyHTML.UTF8_Set_chkbox.Checked = True
                EasyHTML.cssImport_lst.Items.Add("https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css")
                EasyHTML.CodeEditorBox.Text = "<h1 align=""center"">Bulma Template</h1><br><p align=""center"">This is the Bulma Template generated by EasyHTML.</p>"
                Me.Close()
#End Region
            ElseIf cmb_Theme.Text = "Materialize" Then
#Region "Materialize"
                ' Generate Materialize Template
                EasyHTML.mobileViewport_chkbox.Checked = True
                EasyHTML.UTF8_Set_chkbox.Checked = True
                EasyHTML.cssImport_lst.Items.Add("https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css")
                EasyHTML.cssImport_lst.Items.Add("https://fonts.googleapis.com/icon?family=Material+Icons")
                EasyHTML.CodeEditorBox.Text = "<h1 align=""center"">Materialize Template</h1><br><p align=""center"">This is the Materialize Template generated by EasyHTML.</p>"
                EasyHTML.jsImport_lst.Items.Add("https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js")
                Me.Close()
#End Region
            ElseIf cmb_Theme.Text = "Pure" Then
#Region "Pure"
                ' Generate Pure Template
                EasyHTML.mobileViewport_chkbox.Checked = True
                EasyHTML.UTF8_Set_chkbox.Checked = True
                EasyHTML.cssImport_lst.Items.Add("https://unpkg.com/purecss@2.0.3/build/pure-min.css")
                EasyHTML.CodeEditorBox.Text = "<h1 align=""center"">Pure Template</h1><br><p align=""center"">This is the Pure Template generated by EasyHTML.</p>"
                Me.Close()
#End Region
            ElseIf cmb_Theme.Text = "Foundation" Then
#Region "Foundation"
                ' Generate Foundation Template
                EasyHTML.mobileViewport_chkbox.Checked = True
                EasyHTML.UTF8_Set_chkbox.Checked = True
                EasyHTML.cssImport_lst.Items.Add("https://cdn.jsdelivr.net/npm/foundation-sites@6.6.3/dist/css/foundation.min.css")
                EasyHTML.CodeEditorBox.Text = "<h1 align=""center"">Foundation Template</h1><br><p align=""center"">This is the Foundation Template generated by EasyHTML.</p>"
                EasyHTML.jsImport_lst.Items.Add("https://cdn.jsdelivr.net/npm/foundation-sites@6.6.3/dist/js/foundation.min.js")
                Me.Close()
#End Region
            ElseIf cmb_Theme.Text = "Semantic UI" Then
#Region "Semantic UI"
                ' Generate Semantic UI Template
                EasyHTML.mobileViewport_chkbox.Checked = True
                EasyHTML.UTF8_Set_chkbox.Checked = True
                EasyHTML.cssImport_lst.Items.Add("https://github.com/Semantic-Org/Semantic-UI/raw/master/dist/semantic.min.css")
                EasyHTML.CodeEditorBox.Text = "<h1 align=""center"">Semantic UI Template</h1><br><p align=""center"">This is the Semantic UI Template generated by EasyHTML.</p>"
                EasyHTML.jsImport_lst.Items.Add("https://github.com/Semantic-Org/Semantic-UI/raw/master/dist/semantic.min.js")
                Me.Close()
#End Region
            ElseIf cmb_Theme.Text = "Milligram" Then
#Region "Milligram"
                ' Generate Milligram Template
                EasyHTML.mobileViewport_chkbox.Checked = True
                EasyHTML.UTF8_Set_chkbox.Checked = True
                EasyHTML.cssImport_lst.Items.Add("https://fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic")
                EasyHTML.cssImport_lst.Items.Add("https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css")
                EasyHTML.cssImport_lst.Items.Add("https://cdnjs.cloudflare.com/ajax/libs/milligram/1.4.0/milligram.css")
                EasyHTML.CodeEditorBox.Text = "<h1 align=""center"">Milligram Template</h1><br><p align=""center"">This is the Milligram Template generated by EasyHTML.</p>"
                Me.Close()
#End Region
            ElseIf cmb_Theme.Text = "Skeleton" Then
#Region "Skeleton"
                ' Generate Skeleton Template
                EasyHTML.mobileViewport_chkbox.Checked = True
                EasyHTML.UTF8_Set_chkbox.Checked = True
                EasyHTML.cssImport_lst.Items.Add("//fonts.googleapis.com/css?family=Raleway:400,300,600")
                EasyHTML.cssImport_lst.Items.Add("https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css")
                EasyHTML.cssImport_lst.Items.Add("https://github.com/dhg/Skeleton/raw/master/css/skeleton.css")
                EasyHTML.CodeEditorBox.Text = "<div class=""container""><div class=""row""><div class=""one-half column"" style=""margin-top: 25%""><h4>Basic Page</h4><p>This index.html page is a placeholder with the CSS, font and favicon. It's just waiting for you to add some content! If you need some help hit up the <a href=""http://www.getskeleton.com"">Skeleton documentation</a>.<br>This page was the basic page template from Skeleton's GitHub Page. Generated using EasyHTML</p></div></div></div>"
                Me.Close()
#End Region
            ElseIf cmb_Theme.Text = "Tailwind" Then
#Region "Tailwind"
                ' Generate Tailwind Template
                EasyHTML.mobileViewport_chkbox.Checked = True
                EasyHTML.UTF8_Set_chkbox.Checked = True
                EasyHTML.cssImport_lst.Items.Add("https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css")
                EasyHTML.CodeEditorBox.Text = "<h1 align=""center"">Tailwind Template</h1><br><p align=""center"">This is the Tailwind Template generated by EasyHTML.</p>"
                Me.Close()
#End Region
            ElseIf cmb_Theme.Text = "SPECTRE" Then
#Region "SPECTRE"
                ' Generate Spectre Template
                EasyHTML.mobileViewport_chkbox.Checked = True
                EasyHTML.UTF8_Set_chkbox.Checked = True
                EasyHTML.cssImport_lst.Items.Add("https://unpkg.com/spectre.css/dist/spectre.min.css")
                EasyHTML.cssImport_lst.Items.Add("https://unpkg.com/spectre.css/dist/spectre-exp.min.css")
                EasyHTML.cssImport_lst.Items.Add("https://unpkg.com/spectre.css/dist/spectre-icons.min.css")
                EasyHTML.CodeEditorBox.Text = "<h1 align=""center"">SPECTRE Template</h1><br><p align=""center"">This is the SPECTRE Template generated by EasyHTML.</p>"
                Me.Close()
#End Region
            ElseIf cmb_Theme.Text = "Picnic" Then
#Region "Picnic"
                ' Generate Picnic Template
                EasyHTML.mobileViewport_chkbox.Checked = True
                EasyHTML.UTF8_Set_chkbox.Checked = True
                EasyHTML.cssImport_lst.Items.Add("https://cdn.jsdelivr.net/npm/picnic")
                EasyHTML.CodeEditorBox.Text = "<h1 align=""center"">Picnic Template</h1><br><p align=""center"">This is the Picnic Template generated by EasyHTML.</p>"
                Me.Close()
#End Region
            ElseIf cmb_Theme.Text = "Dead Simple Grid" Then
#Region "Dead Simple Grid"
                ' Generate Dead Simple Grid Template
                EasyHTML.mobileViewport_chkbox.Checked = True
                EasyHTML.UTF8_Set_chkbox.Checked = True
                EasyHTML.cssImport_lst.Items.Add("https://github.com/mourner/dead-simple-grid/raw/gh-pages/css/grid.css")
                EasyHTML.cssImport_lst.Items.Add("https://github.com/mourner/dead-simple-grid/raw/gh-pages/css/screen.css")
                EasyHTML.CodeEditorBox.Text = "<h1 align=""center"">Dead Simple Grid Template</h1><br><p align=""center"">This is the Dead Simple Grid Template generated by EasyHTML.</p>"
                Me.Close()
#End Region
            ElseIf cmb_Theme.Text = "HTML 5 Test Page" Then
#Region "HTML 5 Test Page"
                ' Generate HTML 5 Test Page
                EasyHTML.CodeEditorBox.Text = "<!DOCTYPE html PUBLIC "" -// W3C // DTD XHTML 1.0 Transitional//EN"" ""http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"" < html xmlns=""http://www.w3.org/1999/xhtml""><head><title>HTML 5 Test Page</title><style type=""text/css"">body,html{margin:0;padding:0;height:100%;overflow:hidden}#content{position:absolute;left:0;right:0;bottom:0;top:0px}</style></head><body><div id=""content""> <iframe width=""100%"" height=""100%"" frameborder=""0"" src=""https://cbracco.github.io/html5-test-page/"" /></div></body></html>"
                Me.Close()
#End Region
            Else
                MessageBox.Show("So. Ye found a secret. This really doesn't happen all that often. Sometimes it is just a error I made while coding, sometimes it just happens on its own. If you think this is a coding mistake then please report it to me.")
            End If
        End If
    End Sub
End Class