Public Class ThemeSelect
    Private Sub Timer1_Tick(sender As Object, e As EventArgs) Handles Timer1.Tick
        If rad_Template.Checked = True Then
            grp_SelectTemplate.Enabled = True
            'cmb_Theme.Enabled = True
        ElseIf rad_Template.Checked = False Then
            grp_SelectTemplate.Enabled = False
            'cmb_Theme.Enabled = False
        End If
    End Sub

    Private Sub ThemeSelect_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        cmb_Theme.SelectedIndex = 1
        rad_Template.Checked = False
        rad_Blank.Checked = True
        Timer1.Start()
    End Sub

    Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        If rad_Blank.Checked = True And rad_Template.Checked = False Then
            Me.Close()
        ElseIf rad_Blank.Checked = False And rad_Template.Checked = True Then
            If cmb_Theme.Text = "" Then
                MessageBox.Show("Please select a template.", "No Template Selected", MessageBoxButtons.OK, MessageBoxIcon.Error)
            ElseIf cmb_Theme.Text = "UI Kit" Then
                EasyHTML.mobileViewport_chkbox.Checked = True
                EasyHTML.cssImport_lst.Items.Add("https://cdnjs.cloudflare.com/ajax/libs/uikit/3.5.4/css/uikit.min.css")
                EasyHTML.cssImport_lst.Items.Add("css/styles.css")
                EasyHTML.CodeEditorBox.Text = "<h1 align=""center"">UI Kit Template</h1><br><p align=""center"">This is the UI Kit Template generated by EasyHTML.</p>"
                EasyHTML.jsImport_lst.Items.Add("https://cdnjs.cloudflare.com/ajax/libs/uikit/3.5.4/js/uikit.min.js")
                EasyHTML.jsImport_lst.Items.Add("https://cdnjs.cloudflare.com/ajax/libs/uikit/3.5.4/js/uikit-icons.min.js")
                Me.Close()
            ElseIf cmb_Theme.Text = "Bootstrap" Then
                EasyHTML.mobileViewport_chkbox.Checked = True
                EasyHTML.cssImport_lst.Items.Add("https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css")
                EasyHTML.pageTitle_txtBox.Text = "Hello, World!"
                EasyHTML.CodeEditorBox.Text = "<h1 align=""center"">Bootstrap Template</h1><br><p align=""center"">This is the Bootstrap Template generated by EasyHTML.</p>"
                EasyHTML.jsImport_lst.Items.Add("https://code.jquery.com/jquery-3.5.1.slim.min.js")
                EasyHTML.jsImport_lst.Items.Add("https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js")
                EasyHTML.jsImport_lst.Items.Add("https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js")
                Me.Close()
            End If
        End If
    End Sub
End Class