Public Class ThemeSelect
    Private Sub Timer1_Tick(sender As Object, e As EventArgs) Handles Timer1.Tick
        If rad_Template.Checked = True Then
            grp_SelectTemplate.Enabled = True
            'cmb_Theme.Enabled = True
        ElseIf rad_Template.Checked = False Then
            grp_SelectTemplate.Enabled = False
            'cmb_Theme.Enabled = False
        End If
    End Sub

    Private Sub ThemeSelect_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        cmb_Theme.SelectedIndex = 1
        rad_Template.Checked = False
        rad_Blank.Checked = True
        Timer1.Start()
    End Sub

    Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        If rad_Blank.Checked = True And rad_Template.Checked = False Then
            Me.Close()
        ElseIf rad_Blank.Checked = False And rad_Template.Checked = True Then
            If cmb_Theme.Text = "" Then
                MessageBox.Show("Please select a template.", "No Template Selected", MessageBoxButtons.OK, MessageBoxIcon.Error)
            ElseIf cmb_Theme.Text = "UI Kit" Then
#Region "UI Kit"
                EasyHTML.mobileViewport_chkbox.Checked = True
                EasyHTML.UTF8_Set_chkbox.Checked = True
                EasyHTML.metatags_chkbox.Checked = True
                EasyHTML.siteAuthor_txtbox.Text = "TheCrafters001"
                EasyHTML.title_txtBox.Text = "EasyHTML Template"
                EasyHTML.revisit_txtBox.Text = "1"
                EasyHTML.description_txtBox.Text = "EasyHTML Template"
                EasyHTML.keywords_txtBox.Text = "easyhtml, template"
                EasyHTML.cssImport_lst.Items.Add("https://cdnjs.cloudflare.com/ajax/libs/uikit/3.5.4/css/uikit.min.css")
                EasyHTML.cssImport_lst.Items.Add("css/styles.css")
                EasyHTML.CodeEditorBox.Text = "<h1 align=""center"">UI Kit Template</h1><br><p align=""center"">This is the UI Kit Template generated by EasyHTML.</p>"
                EasyHTML.jsImport_lst.Items.Add("https://cdnjs.cloudflare.com/ajax/libs/uikit/3.5.4/js/uikit.min.js")
                EasyHTML.jsImport_lst.Items.Add("https://cdnjs.cloudflare.com/ajax/libs/uikit/3.5.4/js/uikit-icons.min.js")
                Me.Close()
#End Region
            ElseIf cmb_Theme.Text = "Bootstrap" Then
#Region "Bootstrap"
                EasyHTML.mobileViewport_chkbox.Checked = True
                EasyHTML.UTF8_Set_chkbox.Checked = True
                EasyHTML.metatags_chkbox.Checked = True
                EasyHTML.siteAuthor_txtbox.Text = "TheCrafters001"
                EasyHTML.title_txtBox.Text = "EasyHTML Template"
                EasyHTML.revisit_txtBox.Text = "1"
                EasyHTML.description_txtBox.Text = "EasyHTML Template"
                EasyHTML.keywords_txtBox.Text = "easyhtml, template"
                EasyHTML.cssImport_lst.Items.Add("https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css")
                EasyHTML.pageTitle_txtBox.Text = "Hello, World!"
                EasyHTML.CodeEditorBox.Text = "<h1 align=""center"">Bootstrap Template</h1><br><p align=""center"">This is the Bootstrap Template generated by EasyHTML.</p>"
                EasyHTML.jsImport_lst.Items.Add("https://code.jquery.com/jquery-3.5.1.slim.min.js")
                EasyHTML.jsImport_lst.Items.Add("https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js")
                EasyHTML.jsImport_lst.Items.Add("https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js")
                Me.Close()
#End Region
            ElseIf cmb_Theme.Text = "W3.CSS" Then
#Region "W3.CSS"
                EasyHTML.mobileViewport_chkbox.Checked = True
                EasyHTML.UTF8_Set_chkbox.Checked = True
                EasyHTML.metatags_chkbox.Checked = True
                EasyHTML.siteAuthor_txtbox.Text = "TheCrafters001"
                EasyHTML.title_txtBox.Text = "EasyHTML Template"
                EasyHTML.revisit_txtBox.Text = "1"
                EasyHTML.description_txtBox.Text = "EasyHTML Template"
                EasyHTML.keywords_txtBox.Text = "easyhtml, template"
                EasyHTML.cssImport_lst.Items.Add("https://www.w3schools.com/w3css/4/w3.css")
                EasyHTML.CodeEditorBox.Text = "<h1 align=""center"">W3.CSS Template</h1><br><p align=""center"">This is the W3.CSS Template generated by EasyHTML.</p>"
                EasyHTML.jsImport_lst.Items.Add("https://www.w3schools.com/lib/w3.js")
                Me.Close()
#End Region
            ElseIf cmb_Theme.Text = "Bulma" Then
#Region "Bulma"
                EasyHTML.mobileViewport_chkbox.Checked = True
                EasyHTML.UTF8_Set_chkbox.Checked = True
                EasyHTML.cssImport_lst.Items.Add("https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css")
                EasyHTML.CodeEditorBox.Text = "<h1 align=""center"">Bulma Template</h1><br><p align=""center"">This is the Bulma Template generated by EasyHTML.</p>"
                Me.Close()
#End Region
            Else
                MessageBox.Show("So. Ye found a secret. This really doesn't happen all that often. Sometimes it is just a error I made while coding, sometimes it just happens on its own. If you think this is a coding mistake then please report it to me.")
            End If
        End If
    End Sub
End Class